server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /apiws {
    proxy_pass http://hsgram_server-teamgram-1:8801;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
  }

  location /assets/ {
    try_files $uri =404;
  }

  location ~* \.(js|css|map|wasm|woff2?|ttf|png|jpg|jpeg|gif|svg|ico|webmanifest|xml)$ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
