import langSign from './langSign';

const zhCN = {
  ...langSign,
  'Login.Title': '登录 HSgram',
  'Login.PhoneLabel': '手机号码',
  'Login.PhoneLabelInvalid': '手机号码无效',
  'Login.StartText': '请确认国家代码\n并输入你的手机号码。',
  'Login.Code.SentSms': '我们已经通过短信\n向你发送了验证码。',
  'Login.Code.SentInApp': '我们已经在 HSgram 中\n向你发送了验证码。',
  'Login.Code.SentCall': '我们将通过电话告知你\n验证码。',
  'Login.Code.SentEmail': '请检查邮箱 **%s**（别忘了垃圾邮件文件夹）并输入刚刚发送给你的验证码。',
  'Login.Code.SentUnknown': '请检查所有可用渠道\n获取验证码（类型：%s）',
  'Login.Password.Title': '输入密码',
  'Login.Password.Subtitle': '你的账号已启用\n额外密码保护',
  'Login.Register.Subtitle': '输入你的姓名并添加\n头像',
  'PleaseWait': '请稍候...',
  'ForgotPassword': '[忘记密码？]()',
  'TroubleEmail': '[无法访问这个邮箱？]()',
  'Login.ResetPassword.Title': '重置密码',
  'Login.ResetPassword.Subtitle': '请输入刚刚发送到\n邮箱 **%s** 的验证码。',
  'Login.ResetPassword.Cancel': '取消',
  'Login.ResetPassword.NoEmailText': '你没有设置恢复邮箱，因此只能尝试记住密码或重置账号。',
  'Login.ResetPassword.TroubleEmailText': '如果无法恢复邮箱访问权限，你只能尝试记住密码或重置账号。',
  'Login.ResetPassword.ResetAccount': '重置账号',
  'Login.ResetAccount.Title': '警告',
  'Login.ResetAccount.Text': '此操作无法撤销。\n\n重置账号后，所有消息和聊天都会被删除。',
  'Login.ResetAccountFail.Title': '抱歉',
  'Login.ResetAccountFail.TextCancelled': '你最近的账号重置尝试已被当前活跃用户取消。请 7 天后再试。',
  'Login.ResetAccountFail.TextWait': '由于此账号处于活跃状态并受密码保护，出于安全考虑，我们将在 1 周后删除它。\n\n你可以随时取消此流程。\n\n你可以在以下时间后重置账号：%s。',
  'Login.ResetEmail.Title': '重置邮箱',
  'Login.ResetEmail.Text': '如果你已在另一台设备上登录 HSgram，可以更改登录邮箱。\n\n否则，如果你无法访问此邮箱，可以在 **%s** 后用 **短信** 验证码重置。',
  'Login.ResetEmail.Pending': '邮箱将在 %s 后重置。[现在通过短信重置]()',
  'Login.ResetEmail.PleaseWait': '正在重置邮箱，请稍候...',
  'Login.ResetEmail.NeedPremium': '需要 Premium',
  'Login.ResetEmail.NeedPremiumText': '由于你所在国家/地区短信费用较高，需要 **Premium** 账号才能立即通过短信重置邮箱。\n\n你可以请朋友为你的账号赠送 Premium 订阅。',
  'Login.Passkey': '使用通行密钥登录',
  'Login.Passkey.Error': '出错了',
  'Login.Passkey.Error.NotFound': '此通行密钥未绑定任何账号',
  'Code': '验证码',
  'LoginPassword': '密码',
  'YourName': '你的姓名',
  'FirstName': '名（必填）',
  'LastName': '姓（可选）',
  'StartMessaging': '开始聊天',
  'Country': '国家/地区',
  'Contacts.PhoneNumber.Placeholder': '手机号码',
  'Login.Next': '下一步',
  'Login.ContinueOnLanguage': '继续使用中文',
  'Login.QR.Title': '通过二维码登录 HSgram',
  'Login.QR.Help1': '打开手机端 HSgram',
  'Login.QR.Help2': '进入 **设置** > **设备** > **连接桌面设备**',
  'Login.QR.Help3': '将手机摄像头对准此屏幕完成确认',
  'Login.QR.Cancel': '使用手机号码登录',
  'Login.QR.Login': '使用二维码登录',
  'PhoneNumber.Code.Fragment.Info': '在 [Fragment](%1$@) 的 Numbers 区域获取验证码',
  'PHONE_CODE_INVALID': '验证码无效',
  'PHONE_CODE_EXPIRED': '验证码已过期',
  'PASSWORD_HASH_INVALID': '密码错误'
};

export default zhCN;
