import lang from './lang';

const zhCN = {
  ...lang,
  'Animations': '动画',
  'AttachAlbum': '相册',
  'DarkMode': '深色模式',
  'ChatList.Main.EmptyPlaceholder.Title': '你的聊天会显示在这里',
  'ChatList.Main.EmptyPlaceholder.Subtitle': '你在 HSgram 上有 %s',
  'ChatList.Main.EmptyPlaceholder.SubtitleNoContacts': '请使用手机端 HSgram 同步联系人',
  'ConnectionStatus.ForceReconnect': '立即重连',
  'ConnectionStatus.Reconnect': '重新连接',
  'ConnectionStatus.Reconnecting': '正在重新连接...',
  'ConnectionStatus.Waiting': '正在等待网络...',
  'Suggestion.Notifications': '不要错过任何消息！%s',
  'Suggestion.Notifications.Subtitle': '开启通知，及时收到新消息。',
  'Suggestion.Notifications.Dismissed': '你可以稍后在设置里重新开启通知。',
  'NewPrivateChat': '新建私聊',
  'Checkbox.Enabled': '已开启',
  'Checkbox.Disabled': '已关闭',
  'SearchPlaceholder': '搜索...',
  'Profile.Info.Group': '群组信息',
  'Profile.Info.Channel': '频道信息',
  'Set': '确定',
  'AccDescrEditing': '正在编辑',
  'ActionCreateChannel': '频道已创建',
  'ActionCreateGroup': 'un1 创建了此群组',
  'ActionChangedTitle': 'un1 将群组名称更改为 un2',
  'ActionRemovedPhoto': 'un1 移除了群组头像',
  'ActionChangedPhoto': 'un1 更改了群组头像',
  'ActionChangedVideo': 'un1 更改了群组动态头像',
  'ActionAddUser': 'un1 添加了 un2',
  'ActionAddUserSelf': 'un1 返回了此群组',
  'ActionAddUserSelfYou': '您返回了此群组',
  'ActionAddUserSelfMega': 'un1 加入了这个群组',
  'ActionLeftUser': 'un1 退出了群组',
  'ActionKickUser': 'un1 移除了 un2',
  'ActionInviteUser': 'un1 通过邀请链接加入了此群组',
  'ActionPinnedNoText': 'un1 置顶了一条消息',
  'ActionMigrateFromGroup': '此群组已升级为超级群组',
  'ActionYouScored': '您获得了 %1$s 分',
  'ActionUserScored': 'un1 获得了 %1$s 分',
  'ActionYouScoredInGame': '你在 un2 中获得 %1$s 分',
  'ActionUserScoredInGame': 'un1 在 un2 中获得 %1$s 分',
  'AttachPhoto': '图片',
  'AttachVideo': '视频',
  'AttachGif': 'GIF',
  'AttachLocation': '位置',
  'AttachLiveLocation': '实时位置',
  'AttachContact': '联系人',
  'AttachSticker': '[贴纸]',
  'AttachAudio': '语音留言',
  'AttachRound': '视频留言',
  'AttachGame': '游戏',
  'Bot': '机器人',
  'ChannelMegaJoined': '您加入了这个群组',
  'EnterChannelName': '频道名称',
  'DescriptionOptionalPlaceholder': '简介 (可选)',
  'DescriptionPlaceholder': '简介',
  'DiscussionStarted': '讨论已开始',
  'Draft': '草稿',
  'FilterAlwaysShow': '包括的对话',
  'FilterNeverShow': '排除的对话',
  'FilterInclude': '包括的对话',
  'FilterExclude': '排除的对话',
  'FilterChatTypes': '对话类型',
  'FilterChats': '对话',
  'FilterNew': '新建文件夹',
  'Filters': '文件夹',
  'FilterRecommended': '推荐文件夹',
  'FromYou': '您',
  'Add': '添加',
  'UsernameHelpLink': '此链接会打开一个与您的对话窗口：\n%1$s',
  'NewChannel': '新建频道',
  'NewGroup': '新建群组',
  'Members': {
    'one_value': '%1$d 位成员',
    'other_value': '%1$d 位成员'
  },
  'Users': {
    'one_value': '%1$d 位用户',
    'other_value': '%1$d 位用户'
  },
  'Groups': {
    'one_value': '%1$d 个群组',
    'other_value': '%1$d 个群组'
  },
  'Contacts': '联系人',
  'SavedMessages': '收藏夹',
  'Settings': '设置',
  'SettingsHelp': '帮助',
  'General': '通用',
  'TextSize': '消息文字大小',
  'ChatBackground': '对话背景',
  'EnableAnimations': '动画切换效果',
  'AutoDownloadMedia': '自动下载媒体文件',
  'AutodownloadContacts': '联系人',
  'AutodownloadPrivateChats': '私聊',
  'AutodownloadGroupChats': '群聊',
  'AutodownloadChannels': '频道',
  'AutoplayGIF': 'GIF',
  'AutoplayVideo': '视频',
  'NotificationsForGroups': '群组通知',
  'NotificationsForPrivateChats': '私聊通知',
  'NotificationsForChannels': '频道通知',
  'NotificationsPrivateChats': '私聊',
  'NotificationsGroups': '群组',
  'NotificationsChannels': '频道',
  'NotificationsOther': '其它',
  'MarkAsUnread': '标记为未读',
  'MarkAsRead': '标记为已读',
  'MarkAllAsRead': '全部标记为已读',
  'ContactJoined': '联系人加入 Telegram',
  'Loading': '载入中...',
  'Unblock': '取消屏蔽',
  'BlockedUsers': '已屏蔽的用户',
  'BlockedUsersInfo': '被屏蔽的用户将无法与您联系，也无法看到您的最后上线时间。',
  'BlockedEmpty': '无',
  'TwoStepVerification': '两步验证',
  'TwoStepVerificationTitle': '两步验证',
  'PinnedMessage': '置顶消息',
  'PrivacyExceptions': '例外',
  'PrivacyLastSeen': '最后上线 & 在线',
  'PrivacySettings': '隐私和安全',
  'PrivacyTitle': '隐私',
  'PrivacyPhone': '手机号码',
  'PrivacyPhoneTitle': '谁可以看到我的手机号码？',
  'PrivacyPhoneTitle2': '谁可以通过我的手机号找到我？',
  'PrivacyPhoneInfo': '已将您的手机号码保存在其通讯录中的用户将可关联到你在 Telegram 的身份。',
  'PrivacyPhoneInfo3': '只有您的联系人才能通过手机号码匹配到您。',
  'PrivacyProfilePhoto': '头像',
  'PrivacyProfilePhotoTitle': '谁可以看到我的头像？',
  'PrivacyP2PHeader': '端到端连接',
  'PrivacyForwardsTitle': '谁可以在转发我的消息时附加我的帐号链接？',
  'Reminders': '提醒',
  'ScheduledMessages': '定时消息',
  'LastSeenTitle': '谁可以看见我的最后上线时间？',
  'SessionsTitle': '已登录的设备',
  'CurrentSession': '当前设备',
  'TerminateAllSessions': '将其他设备退出登录',
  'TerminateSessionText': '您确定要结束该会话吗？',
  'OtherSessions': '其他设备',
  'AreYouSureDeleteSingleMessage': '您确定要删除这条消息吗？',
  'AreYouSureDeleteFewMessages': '您确定要删除这些消息吗？',
  'AreYouSureDeleteSingleMessageMega': '您确定要为所有人删除此消息吗？',
  'AreYouSureDeleteFewMessagesMega': '您确定要为所有人删除这些消息吗？',
  'AreYouSureDeleteAndExitName': '您确定要删除并退出 **%1$s** 吗？',
  'AreYouSureDeleteThisChatSavedMessages': '您确定要删除收藏夹吗？',
  'AreYouSureDeleteThisChatWithUser': '您确定要删除与 **%1$s** 的对话吗？',
  'AreYouSureSessionTitle': '结束会话',
  'AreYouSureSessionsTitle': '终止活动会话',
  'AreYouSureSessions': '您确定要将所有其他设备退出登录吗？',
  'Terminate': '结束',
  'WhoCanCallMe': '谁可以给我打电话？',
  'WhoCanAddMe': '谁可以邀请我进入群组？',
  'ArchivedChats': '归档聊天',
  'Cancel': '取消',
  'Decline': '拒绝',
  'HistoryCleared': '历史聊天记录已被清除',
  'Archive': '归档',
  'Unarchive': '取消归档',
  'Delete': '删除',
  'Reply': '回复',
  'Edit': '编辑',
  'Forward': '转发',
  'CopyLink': '复制链接',
  'Copy': '复制',
  'Search': '搜索',
  'LinkCopied': '链接已复制到剪贴板',
  'GroupAddMembers': '添加成员',
  'SendMessageTo': '添加成员...',
  'JumpToDate': '跳转',
  'Caption': '说明',
  'Message': '消息',
  'Poll': '投票',
  'SharedFilesTab2': '文件',
  'SharedMediaTab2': '媒体',
  'SharedLinksTab2': '链接',
  'SharedMusicTab2': '音频',
  'SharedVoiceTab2': '语音留言',
  'NewPoll': '发起投票',
  'PollOptions': '候选项',
  'AskAQuestion': '联系客服',
  'AddAnExplanationInfo': '用户选择了错误的答案后，会看到此文本，因此非常适合教育用途。',
  'PhoneCopied': '手机号码已复制到剪贴板',
  'UserBio': '个人简介',
  'Username': '用户名',
  'UsernameHelp': '您可以在 **HSgram** 上设置一个用户名。设置后，别人将能够在不知道您的手机号码的情况下，通过此用户名找到您并与您联系。\n\n您可以使用 **a–z**、**0–9** 及下划线。最小长度为 **5** 个字符。',
  'Phone': '手机号码',
  'Notifications': '通知',
  'AreYouSureDeleteContact': '您确定要删除此联系人吗？',
  'AreYouSureDeleteAndExit': '您确定要删除并退出此群组吗？',
  'DeleteContact': '删除联系人',
  'GroupType': '群组类型',
  'ChannelType': '频道类型',
  'TypePrivate': '私有',
  'TypePublic': '公开',
  'TypePrivateGroup': '私有',
  'TypePublicGroup': '公开',
  'GroupMembers': '成员',
  'DeleteMega': '删除群组',
  'DeleteMegaMenu': '删除群组',
  'DeleteAndExitButton': '删除并退出群组',
  'ChannelDelete': '删除频道',
  'ChannelDeleteMenu': '删除频道',
  'ChannelPermissions': '权限',
  'ChannelPermissionsHeader': '这个群组的成员可以做什么？',
  'ChannelAddException': '添加例外',
  'ChannelBlockedUsers': '被移除的用户',
  'NoBlockedUsers': '暂无被移除的用户',
  'UserRestrictions': '用户权限',
  'UserRestrictionsDisabled': '在群组权限中，所有成员被设置为没有此权限。',
  'UserRestrictionsCanDo': '这位用户可以做什么？',
  'UserRestrictionsRead': '查看消息',
  'UserRestrictionsSend': '发送消息',
  'UserRestrictionsSendMedia': '发送媒体',
  'UserRestrictionsSendPolls': '发起投票',
  'UserRestrictionsSendStickers': '发送贴纸和 GIF',
  'UserRestrictionsEmbedLinks': '显示链接预览',
  'UserRestrictionsChangeInfo': '修改群组信息',
  'UserRestrictionsPinMessages': '置顶消息',
  'UserRestrictionsInviteUsers': '添加成员',
  'UserRestrictionsNoSend': '无法发送消息',
  'UserRestrictionsNoSendMedia': '无法发送媒体',
  'UserRestrictionsNoSendPolls': '无法发起投票',
  'UserRestrictionsNoSendStickers': '无法发送贴纸',
  'UserRestrictionsNoEmbedLinks': '无法使用预览',
  'UserRestrictionsNoChangeInfo': '无法更改群组信息',
  'UserRestrictionsNoPinMessages': '无法置顶消息',
  'UserRestrictionsNoInviteUsers': '无法邀请成员',
  'UserRestrictionsBlock': '封禁并从群组中移除',
  'ChannelPublic': '公开频道',
  'MegaPublic': '公开群组',
  'ChannelPublicInfo': '公开频道可以被搜索，任何人都可以加入。',
  'MegaPublicInfo': '任何人都可以搜索和加入公开群组，并查看其历史记录。',
  'ChannelPrivate': '私有频道',
  'MegaPrivate': '私有群组',
  'ChannelPrivateInfo': '私人频道只能通过邀请链接加入。',
  'MegaPrivateInfo': '私人群组只能通过他人邀请或通过邀请链接加入。',
  'ChannelPrivateLinkHelp': '用戶可以通过以上链接加入您的频道。您可以随时撤销此链接。',
  'MegaPrivateLinkHelp': '用戶可以通过上方链接加入您的群组。您可以随时撤销这个链接。',
  'RevokeButton': '撤销',
  'RevokeLink': '撤销链接',
  'RevokeAlert': '您确定要撤销此邀请链接吗？一旦撤销，其他人将不能通过此链接加入本群组。',
  'SetUrlPlaceholder': '链接',
  'SearchGifsTitle': '搜索 GIF',
  'PinMessageAlert': '您确定要在群组中置顶此消息？',
  'PinMessageAlertTitle': '置顶消息',
  'PinMessageAlertChannel': '您确定要在频道中置顶此消息？',
  'PinMessageAlertChat': '您确定要在对话中置顶此消息？',
  'UnpinMessageAlertTitle': '取消置顶消息',
  'UnpinMessageAlert': '您确定要取消置顶此消息吗？',
  'PinNotify': '通知所有成员',
  'PinMessage': '置顶',
  'UnpinMessage': '取消置顶',
  'PinAlsoFor': '也为 %1$s 置顶',
  'DeleteMessagesTitle': '删除 %1$s',
  'DeleteSingleMessagesTitle': '删除消息',
  'DeleteMessagesOption': '撤回我的消息',
  'DeleteMessagesOptionAlso': '同时为 %1$s 删除',
  'DeleteForAll': '为所有成员删除',
  'DeleteMessagesTextGroup': '您还可以通过选中“撤回我的消息”以从其他群组成员的消息记录中删除您发送的 %1$s。',
  'LeaveChannel': '退出频道',
  'LeaveChannelMenu': '退出频道',
  'ChannelLeaveAlertWithName': '您确定要退出 **%1$s** 吗？',
  'LeaveMegaMenu': '退出群组',
  'DeleteChatUser': '删除对话',
  'PleaseEnterCurrentPassword': '请输入您的密码',
  'PleaseEnterFirstPassword': '请输入一个密码',
  'PleaseReEnterPassword': '请再次输入密码',
  'Continue': '继续',
  'YourEmailSkip': '跳过',
  'YourEmailSkipWarning': '警告',
  'YourEmailSkipWarningText': '您确定不设置密码恢复邮箱？\n\n一旦您忘记了密码，您将无法再访问您的 Telegram 帐号，并且我们没有任何恢复帐号数据的方法。',
  'TurnPasswordOffQuestionTitle': '关闭密码',
  'TurnPasswordOffQuestion': '您确定要删除您的密码吗？',
  'Disable': '禁用',
  'TwoStepVerificationSetPassword': '设置密码',
  'TwoStepVerificationPasswordSet': '密码已设置！',
  'TwoStepVerificationPasswordSetInfo': '登录新设备时，除了通过短信获得的代码外，您还需要输入此密码。',
  'TwoStepVerificationPasswordReturnSettings': '返回设置',
  'RecoveryEmail': '恢复邮箱',
  'RecoveryEmailTitle': '恢复邮箱',
  'ResendCode': '重新发送验证码',
  'PasswordAsHintError': '密码提示必须与密码本身不同',
  'AddStickersCount': '添加 %1$s',
  'RemoveStickersCount': '移除 %1$s',
  'HidAccount': '此用户的隐私设置拒绝您查看转发来源',
  'SetColor': '设置纯色背景',
  'Open': '打开',
  'OpenUrlTitle': '打开链接',
  'OpenUrlAlert2': '您想打开 %1$s 吗？',
  'FilterNoChatsToDisplay': '没有对话',
  'FilterNoChatsToDisplayInfo': '当前没有对话属于此文件夹。',
  'SupportStatus': '支持',
  'Lately': '最近上过线',
  'WithinAWeek': '一周内有上线',
  'WithinAMonth': '一个月内曾上线',
  'ALongTimeAgo': '很久前上线',
  'Online': '在线',
  'MessageScheduleSend': '立刻发送',
  'MessageScheduleEditTime': '重新定时',
  'YouLeft': '您已经退出此群组',
  'Recent': '最近',
  'Of': '%1$d / %2$d',
  'NoResult': '无搜索结果',
  'Updating': '刷新中...',
  'Emoji': 'Emoji',
  'AddContactTitle': '添加联系人',
  'HiddenName': '已注销账户',
  'TodayAtFormattedWithToday': '今天 %1$s',
  'formatDateAtTime': '%1$s %2$s',
  'JoinByPeekChannelTitle': '加入频道',
  'JoinByPeekGroupTitle': '加入群组',
  'YouWereKicked': '您已被此群组移除',
  'ViaBot': '通过',
  'NoUsernameFound': '没有 Telegram 帐号使用此用户名。',
  'PrivacyDeleteCloudDrafts': '删除所有云端草稿',
  'AreYouSureClearDraftsTitle': '清空所有草稿',
  'AreYouSureClearDrafts': '您确定要删除所有草稿吗？',
  'BotInfoTitle': '它能做什么？',
  'ChatYourSelf': '转发至此以保存',
  'GroupEmptyTitle1': '您创建了一个**群组**',
  'GroupEmptyTitle2': '群组可以拥有：',
  'GroupDescription1': '最多 200,000 位成员',
  'GroupDescription2': '历史记录永久保留',
  'GroupDescription3': '如 t.me/title 一样的公开链接',
  'GroupDescription4': '设置权限细分的管理员',
  'ChatYourSelfDescription1': '转发消息到这里来保存它们',
  'ChatYourSelfDescription2': '发送媒体和文件来存储它们',
  'ChatYourSelfDescription3': '在任意设备上访问此对话',
  'ChatYourSelfDescription4': '使用搜索来更快地查找信息',
  'ChatYourSelfTitle': '您的云存储',
  'ActionYouCreateGroup': '您创建了此群组',
  'NoMessages': '暂无消息...',
  'NoScheduledMessages': '暂无定时消息...',
  'InviteToGroupError': '抱歉，根据此用户的隐私设置，您不能将其添加到群组。',
  'InviteToChannelError': '抱歉，根据此用户的隐私设置，您不能将其添加到频道。',
  'AddMembersAlertTitle': '添加 %1$s',
  'AddOneMemberAlertTitle': '添加成员',
  'AddMembersAlertNamesText': '您确定要添加 %1$s 到 **%2$s** 吗？',
  'AddMembersAlertCountText': '您确定要添加 %1$s 到 **%2$s** 吗？',
  'AddMembersForwardMessages': '向新成员显示最后100条消息',
  'AddOneMemberForwardMessages': '向 **%1$s** 显示最后100条消息',
  'PinToTopLimitReached2': '抱歉，在主对话列表中，您只能将 %1$s置顶。但是，在“对话文件夹”和“已归档对话”中，则可以将更多对话置顶。',
  'FiltersSetupPinAlert': '设置文件夹',
  'AppName': 'HSgram',
  'OK': '好',
  'PinFolderLimitReached': '抱歉，您无法再将更多的对话置顶。',
  'Send': '发送',
  'ChannelJoin': '加入',
  'Yesterday': '昨天',
  'LeaveAComment': '留言',
  'ViewInChat': '在聊天中查看',
  'LinkNotFound': '很遗憾，你无法访问这条消息。你不是消息来源对话的成员。',
  'Create': '创建',
  'ViewDiscussion': '查看评论',
  'MessageScheduledUntilOnline': '当上线时发送',
  'ReportChat': '举报',
  'ReportChatSpam': '垃圾信息',
  'ReportChatViolence': '暴力',
  'ReportChatPornography': '色情',
  'ReportChatChild': '儿童虐待',
  'ReportChatOther': '其它',
  'ReportChatDescription': '详情',
  'ChatHistory': '新成员历史对话可见性',
  'ShareContact': '分享联系人',
  'SendMessageTitle': '发送消息',
  'SendContactToGroupText': '您要将这个联系人资料分享给 **%1$s** 吗？',
  'ChannelBroadcast': '广播消息',
  'ChannelSilentBroadcast': '无声广播',
  'Comment': '留言',
  'SendAnonymously': '匿名发送',
  'DiscardVoiceMessageTitle': '放弃录制语音留言',
  'DiscardVoiceMessageDescription': '您确定要停止录制并放弃已录制的语音留言吗？',
  'DiscardVoiceMessageAction': '放弃',
  'AddContact': '添加联系人',
  'BlockUser': '屏蔽用户',
  'MobileHidden': '手机号已隐藏',
  'MobileHiddenExceptionInfo': '一旦 %1$s 将您添加为联系人，电话号码将对您可见。',
  'FirstName': '名字（必填）',
  'LastName': '姓氏（可选）',
  'AreYouSureBlockContact2': '您确定要屏蔽 **%1$s** 吗？',
  'UserBlocked': '用户已屏蔽',
  'UserUnblocked': '用户已取消屏蔽',
  'AudioUnknownArtist': '未知艺术家',
  'AudioUnknownTitle': '未知标题',
  'LogOut': '退出当前帐号',
  'EditedMessage': '已编辑',
  'GlobalSearch': '全局搜索',
  'SearchMessages': '消息',
  'SearchAllChatsShort': '对话',
  'ClearButton': '清空',
  'FilterAllChats': '全部对话',
  'FilterAllChatsShort': '全部',
  'Call': '呼叫',
  'VideoCall': '视频通话',
  'CallMessageOutgoing': '拨出电话',
  'CallMessageIncoming': '拨入电话',
  'CallMessageVideoOutgoing': '拨出视频通话',
  'CallMessageVideoIncoming': '拨入视频通话',
  'VoipExchangingKeys': '正在交换密钥',
  'VoipUnmute': '麦克风',
  'RestrictSavingContent': '限制保存内容',
  'RestrictSavingContentInfoGroup': '开启后，成员将无法复制、保存或转发这个群组中的内容。',
  'RestrictSavingContentInfoChannel': '开启后，订阅者将无法复制、保存或转发这个频道中的内容。',
  'ClearOtherSessionsHelp': '退出所有已登录的设备，只保留当前使用的。',
  'FilterNameHint': '文件夹名',
  'BotStart': '开始',
  'BotUnblock': '重新启用',
  'BotStop': '停止使用',
  'BotRestart': '重新启用',
  'ShareYouPhoneNumberTitle': '是否分享您的手机号码？',
  'AreYouSureShareMyContactInfoBot': '机器人将会获取您的手机号码。这可能对机器人与其它服务的集成有用。',
  'DistanceUnitsTitle': '距离单位',
  'DistanceUnitsKilometers': '千米',
  'DistanceUnitsMiles': '英里',
  'PeopleNearby': '附近的人',
  'MakeMyselfVisible': '使我对外可见',
  'MakeMyselfVisibleTitle': '使您的资料公开可见？',
  'MakeMyselfVisibleInfo': '附近的用户将可以查看您的个人资料。这可能会帮助您认识新朋友，但也有可能让您受到不必要的注意。您可以随时关闭这个功能。\n\n另外您的手机号将保持隐藏状态。',
  'StopShowingMe': '使我对外不可见',
  'PeopleNearbyInfo2': '与附近的人交换联系信息并找到新朋友。',
  'NearbyCreateGroup': '创建本地群组',
  'AwayTo': '%1$s 远',
  'MessagePreview': '消息预览',
  'KMetersAway2': '%1$s 千米远',
  'MetersAway2': '%1$s 米远',
  'MilesAway': '%1$s 英里远',
  'FootsAway': '%1$s 英尺远',
  'PeopleNearbyHeader': '附近的人',
  'ChatsNearbyHeader': '附近的群',
  'ChatLocation': '位置',
  'Update': '更新',
  'Reactions': '回应',
  'DataSettings': '数据和存储',
  'GroupsAndChannelsHelp': '控制谁能邀请您进入群组或频道。',
  'SessionsInfo': '控制您在其它设备上的会话。',
  'StickersBotInfo': '欢迎艺术家们使用我们的 @stickers 机器人添加自己的贴纸包。',
  'AutomaticMediaDownload': '自动下载媒体文件',
  'AutoDownloadPhotos': '图片',
  'AutoDownloadVideos': '视频',
  'AutoDownloadFiles': '文件',
  'AutoDownloadOnAllChats': '对所有对话启用',
  'AutoDownloadUpToOnAllChats': '对所有对话不超过 %1$s',
  'AutoDownloadOff': '关闭',
  'AutoDownloadOnUpToFor': '对 %2$s 不超过 %1$s',
  'AutoDownloadOnFor': '对 %1$s 启用',
  'AutoDownloadContacts': '联系人',
  'AutoDownloadPm': '私聊',
  'AutoDownloadGroups': '群组',
  'AutoDownloadChannels': '频道',
  'AutoDownloadAudioInfo': '由于语音留言体积很小，它们将始终自动下载。',
  'AutoplayMedia': '自动播放',
  'AutoDownloadPhotosTitle': '自动下载图片',
  'AutoDownloadVideosTitle': '自动下载视频和 GIF',
  'AutoDownloadFilesTitle': '自动下载文件和音乐',
  'AutoDownloadMaxFileSize': '文件大小限制',
  'AutodownloadSizeLimitUpTo': '不超过 %1$s',
  'ResetAutomaticMediaDownload': '重置自动下载设置',
  'ResetAutomaticMediaDownloadAlertTitle': '重置设置',
  'ResetAutomaticMediaDownloadAlert': '您确定要重置自动下载设置吗？',
  'Reset': '重置',
  'Devices': '设备',
  'LanguageName': '简体中文',
  'EditCantEditPermissionsPublic': '此权限不能在公开群组中开放。',
  'VoipUserMicrophoneIsOff': '%s的麦克风未打开',
  'VoipUserCameraIsOff': '%s的摄像头未打开',
  'VoipPeerIncompatible': '**%1$s** 的应用使用了不兼容的协议。在您能够呼叫他们之前，他们必须先更新他们的应用。',
  'ScamMessage': 'SCAM',
  'TextCopied': '文字已复制到剪贴板',
  'PaymentInvoice': '账单',
  'PaymentTestInvoice': '测试账单',
  'PaymentReceipt': '收据',
  'PaymentCheckout': '结算',
  'PaymentTransactionTotal': '总计',
  'PaymentCheckoutPay': '支付 %1$s',
  'PaymentCheckoutMethod': '支付方式',
  'PaymentCheckoutProvider': '支付服务提供商',
  'PaymentCardNumber': '卡号',
  'PaymentCardSavePaymentInformation': '保存付款信息',
  'PaymentCardInfo': '付款信息',
  'PaymentCardSavePaymentInformationInfoLine1': '您可以保存您的付款信息以便在未来使用。',
  'Done': '完成',
  'PaymentShippingMethod': '配送方式',
  'PaymentNoShippingMethod': '抱歉，无法配送至您的地址。',
  'PaymentShippingInfo': '配送信息',
  'PaymentShippingAddress': '配送地址',
  'PaymentShippingAddress1Placeholder': '地址行 1 (街道)',
  'PaymentShippingAddress2Placeholder': '地址行 2 (街道)',
  'PaymentShippingCityPlaceholder': '城市',
  'PaymentShippingStatePlaceholder': '省份',
  'PaymentShippingCountry': '国家',
  'PaymentShippingZipPlaceholder': '邮政编码',
  'PaymentShippingReceiver': '收件人',
  'PaymentShippingName': '姓名',
  'PaymentShippingEmailPlaceholder': '电子邮箱',
  'PaymentCheckoutPhoneNumber': '手机号码',
  'PaymentCheckoutShippingMethod': '配送方式',
  'PaymentShippingSave': '保存配送信息',
  'PaymentShippingSaveInfo': '您可以保存您的配送信息以便在未来使用。',
  'PrivacyPayments': '付款',
  'PrivacyPaymentsClearInfo': '您可以删除您的配送信息并通知所有的支付服务提供商清除您已保存的信用卡信息。请注意：Telegram 从来不会存储您的信用卡数据。',
  'PrivacyPaymentsClear': '清除付款和配送信息',
  'PrivacyPaymentsClearAlertTitle': '清空付款信息',
  'PrivacyPaymentsClearAlertText': '您确定要清空付款和配送信息吗？',
  'PrivacyClearShipping': '配送信息',
  'PrivacyClearPayment': '付款信息',
  'Save': '保存',
  'PaymentCheckoutName': '姓名',
  'FavoriteStickers': '收藏夹',
  'AddToFavorites': '添加到收藏夹',
  'AddedToFavorites': '此贴纸已添加到收藏',
  'RemovedFromFavorites': '此贴纸已从收藏中移除',
  'RemovedFromRecent': '贴纸已从“最近使用”中移除',
  'DeleteFromFavorites': '从收藏中移除',
  'DeleteFromRecent': '从最近使用中移除',
  'NewChatsFromNonContacts': '未知用户的新对话',
  'ArchiveAndMute': '归档和关闭通知',
  'ArchiveAndMuteInfo': '自动将来自非联系人的新私聊、群组和频道进行归档和关闭通知。',
  'ReactionsAll': '全部',
  'LimitReached': '达到上限',
  'ChannelSignMessages': '消息署名',
  'ChannelSignMessagesInfo': '在管理员发送的消息上附加他们的名字',
  'Topics': '话题',
  'ForumToggleDescription': '话题可以让成员在群组中按主题讨论。',
  'Info': '信息',
  'BotSettings': '设置',
  'OpenMessage': '查看消息',
  'OpenGroup': '查看群组',
  'OpenUrlOption1': '以 **%2$s** 身份登录 %1$s',
  'OpenUrlOption2': '允许 **%1$s** 向我发送消息',
  'OtherWebSessions': '已关联的网站',
  'WebSessionsTitle': '使用 Telegram 登录的网站',
  'TerminateWebSessionText': '您确定要断开与 %1$s 的连接吗？',
  'Disconnect': '断开',
  'TerminateAllWebSessions': '取消与所有网站的关联',
  'AreYouSureWebSessions': '是否取消与所有使用 Telegram 登录的网站的关联？',
  'ClearOtherWebSessionsHelp': '您可以在支持的网站上使用 Telegram 登录。',
  'TerminateWebSessionInfo': '轻触以取消该网站与您 Telegram 帐号的关联',
  'ColorTheme': '色彩主题',
  'SendAsFile': '发送原图',
  'SendAsFiles': '发送原图',
  'ThemeDay': '日间',
  'ThemeNight': '夜间',
  'AutoNightSystemDefault': '系统默认',
  'GlobalAttachMediaRestricted': '此群组不允许发送媒体。',
  'GlobalAttachInlineRestricted': '此群组不允许 Inline 机器人。',
  'GlobalAttachStickersRestricted': '此群组不允许发送贴纸。',
  'GlobalAttachGifRestricted': '此群组不允许发送 GIF。',
  'GlobalSendMessageRestricted': '全员禁言中',
  'ErrorSendRestrictedPollsAll': '抱歉，此群组不允许发起投票。',
  'ChannelBlockUser': '封禁用户',
  'StickersName': '贴纸和装饰',
  'LoopAnimatedStickersInfo': '动态贴纸将在对话中持续播放。',
  'SuggestStickersAll': '全部贴纸包',
  'SuggestStickersInstalled': '已添加的贴纸包',
  'SuggestStickersNone': '从不推荐',
  'ChatAdmin': '管理员',
  'SendMessage': '发送消息',
  'Mention': '提及',
  'OpenChannel2': '打开频道',
  'OpenGroup2': '打开群组',
  'SelectChat': '选择对话',
  'CancelPollAlertTitle': '放弃发起投票',
  'CancelPollAlertText': '您确定要放弃发起新投票吗？',
  'Close': '关闭',
  'LocationUpdatedJustNow': '刚刚更新',
  'InviteLink': '邀请链接',
  'InviteLinks': '邀请链接',
  'FilterEdit': '编辑文件夹',
  'FilterEditAll': '编辑文件夹',
  'FilterIncludeInfo': '选择会出现在此文件夹中的对话和对话类型。',
  'FilterExcludeInfo': '选择不会出现在此文件夹中的对话和对话类型。',
  'FilterRemoveChats': '移除对话',
  'ShareLink': '分享链接',
  'HideAboveTheList': '隐藏于列表上方',
  'SearchEmptyViewTitle': '无结果',
  'ChannelCreator': '创建者',
  'EditAdminPromotedBy': '由 %1$s 设为管理员',
  'EditAdmin': '管理员权限',
  'EditAdminWhatCanDo': '这位管理员可以做什么？',
  'EditAdminChangeChannelInfo': '修改频道信息',
  'EditAdminChangeGroupInfo': '修改群组信息',
  'EditAdminPostMessages': '发布消息',
  'EditAdminEditMessages': '编辑其他人的消息',
  'EditAdminDeleteMessages': '删除其他人的消息',
  'EditAdminGroupDeleteMessages': '删除消息',
  'EditAdminAddAdmins': '添加新管理员',
  'EditAdminSendAnonymously': '匿名发送',
  'StartVoipChatPermission': '管理直播',
  'EditAdminBanUsers': '封禁用户',
  'EditAdminAddUsersViaLink': '生成邀请链接',
  'EditAdminPinMessages': '置顶消息',
  'EditAdminCantEdit': '您无权修改此管理员的权限。',
  'EditCantEditPermissions': '您不能修改此权限。',
  'EditAdminRank': '自定义头衔',
  'EditAdminRankInfo': '一个自定义的头衔将展示给所有成员而不是“%1$s”。',
  'DeleteBanUser': '封禁用户',
  'DeleteReportSpam': '举报垃圾信息',
  'DeleteAllFrom': '删除所有 %1$s 发送的消息',
  'ChannelAddSubscribers': '添加订阅者',
  'ChannelBlacklist': '被封禁的用户',
  'NoBlockedGroup2': '被管理员从群组封禁的用户无法通过邀请链接重新加入。',
  'NoBlockedChannel2': '被管理员删除的成员无法通过邀请链接返回频道。',
  'UserRemovedBy': '被 %1$s 封禁',
  'AddBannedErrorAdmin': '抱歉，您无法封禁此用户。因为此用户是群组管理员，并且您也无权撤销其管理员权限。',
  'SetAsAdmin': '提升为管理员',
  'EditAdminRights': '修改管理权限',
  'KickFromSupergroup': '限制用户权限',
  'KickFromGroup': '从群组中移除',
  'DiscussionInfo': '频道帖子可以在链接的群组中讨论。',
  'LinkedChannel': '链接的频道',
  'DiscussionChannelHelp3': 'Select a group chat that will host comments from your channel.',
  'DiscussionChannelHelp2': '您在频道中发布的所有内容都将被转发到此群组。',
  'DiscussionLinkGroup': '链接群组',
  'DiscussionChannelGroupSetHelp2': '**%1$s** 被设为您的频道中留言的群组。',
  'DiscussionUnlinkGroup': '取消链接群组',
  'DiscussionUnlinkGroupAlert': '你确定要从此群组取消链接 **%1$s** 吗？',
  'DiscussionUnlinkChannelAlert': '您确定要取消 **%1$s** 到此频道的链接吗？',
  'DiscussionUnlink': '取消链接',
  'DiscussionGroupHelp': '**%1$s** 正在将此群组作为其讨论板。',
  'DiscussionGroupHelp2': '此频道中发布的所有新消息都将转发到该群组。',
  'DiscussionUnlinkChannel': '取消链接频道',
  'DiscussionLinkGroupAlertHistory': '对于新成员，历史对话将被设置为可见。',
  'DiscussionCreateGroup': '创建一个新群组',
  'UserRestrictionsBy': '被 %1$s 限制',
  'ChannelLinkInfo': '任何 Telegram 用户都能够通过此链接加入您的频道。',
  'MemberRequests': '入群申请',
  'SubscribeRequests': '订阅申请',
  'DeleteThisChat': '删除此对话',
  'ShareFile': '分享',
  'GrowthChartTitle': '增长',
  'FollowersChartTitle': '订阅者',
  'InteractionsChartTitle': '互动',
  'EnabledNotifications': '开启通知',
  'Statistics': '统计数据',
  'StatisticOverview': '总览',
  'ViewsPerPost': '每个帖子的浏览次数',
  'SharesPerPost': '每个帖子的分享次数',
  'NotificationsMuted': '免打扰',
  'NotificationsUnmuted': '已开通知',
  'LoadingStats': '正在加载统计数据...',
  'LoadingStatsDescription': '正在生成统计数据图表，请稍等片刻。',
  'TopHoursChartTitle': '每小时浏览次数 (UTC)',
  'ViewsBySourceChartTitle': '浏览来源',
  'URL': '链接',
  'NewFollowersBySourceChartTitle': '新订阅者的来源',
  'StatisticViews': '浏览次数',
  'FilterAddTo': '添加到文件夹',
  'ZoomOut': '缩小',
  'LanguagesChartTitle': '语言',
  'IVInteractionsChartTitle': '即时预览互动',
  'RecentPosts': '最近的帖子',
  'GroupMembersChartTitle': '群组成员',
  'NewMembersBySourceChartTitle': '新成员来源',
  'MembersLanguageChartTitle': '成员主要语言',
  'MessagesChartTitle': '消息',
  'ActionsChartTitle': '操作',
  'MembersOverviewTitle': '成员',
  'MessagesOverview': '消息',
  'ViewingMembers': '浏览消息的成员',
  'PostingMembers': '发送消息的成员',
  'TopDaysOfWeekChartTitle': '每周活跃的日子',
  'CharactersPerMessage': '每条消息平均 %s',
  'TopAdmins': '活跃管理员',
  'TopMembers': '活跃成员',
  'TopInviters': '最佳邀请者',
  'PublicShares': '公开分享',
  'PrivateShares': '私密分享',
  'ChannelJoined': '您加入了这个频道',
  'MessageNotFound': '消息不存在',
  'Start': '开始',
  'SlowModeHint': '慢速模式已启用。您可以\n在%1$s后发送下一条消息',
  'SlowmodeSendError': '慢速模式已启用。 您不能一次发送多条消息。',
  'SlowmodeSelectSendError': '慢速模式已启用。您无法选择更多。',
  'SlowmodeSendErrorTooLong': '抱歉，此文本太长，无法作为一条消息发送。\n\n慢速模式已启用。您一次最多只能发送一条消息。',
  'Slowmode': '慢速模式',
  'SlowmodeInfoOff': '选择每个成员在发送下一条消息之前必须等待的时间。',
  'SlowmodeInfoSelected': '成员每%1$s只能发一条消息。',
  'SlowmodeOff': '关闭',
  'SlowmodeSeconds': '%1$d秒',
  'SlowmodeMinutes': '%1$d分钟',
  'SlowmodeHours': '%1$d小时',
  'AccDescrChannel': '频道',
  'NoStickersFound': '未找到贴纸',
  'NoGIFsFound': '未找到 GIF',
  'NoEmojiFound': '未找到 emoji',
  'ViewPackPreview': '查看对应贴纸包',
  'SaveToGIFs': '保存到 GIF 库',
  'UnreadMessages': '未读消息',
  'AutoDownloadSettings.Delimeter': '，',
  'AutoDownloadSettings.LastDelimeter': '和',
  'Call.Accept': '接听',
  'Call.Decline': '拒绝',
  'Call.End': '结束',
  'Call.Camera': '摄像头',
  'Call.Mute': '麦克风',
  'Call.PrivacyErrorMessage': '抱歉，由于 %@ 的隐私设置，您无法与其进行通话。',
  'Call.StatusRequesting': '连接中...',
  'Call.StatusRinging': '响铃中...',
  'Call.StatusConnecting': '连接中...',
  'Call.StatusEnded': '通话结束',
  'Call.StatusFailed': '通话失败',
  'Call.StatusBusy': '忙线',
  'Checkout.NewCard.CardholderNamePlaceholder': '持卡人姓名',
  'Checkout.PasswordEntry.Title': '支付确认',
  'Checkout.PasswordEntry.Pay': '付款',
  'Checkout.PasswordEntry.Text': '您曾经保存过您的银行卡 %@ 。要使用此卡付款，请输入您的两步验证密码。',
  'Checkout.PayPrice': '支付 %@',
  'Checkout.WebConfirmation.Title': '完成支付',
  'ChatList.Context.Mute': '暂停消息通知',
  'ChatList.Context.Unmute': '恢复消息通知',
  'ChatList.Context.Pin': '置顶',
  'ChatList.Context.Unpin': '取消置顶',
  'Channel.EditAdmin.PermissionInviteSubscribers': '添加订阅者',
  'CreateGroup.NameHolder': '群组名称',
  'Error.AnError': '出错了，请稍后重试',
  'FileSize.B': '%@ B',
  'FileSize.KB': '%@ KB',
  'FileSize.MB': '%@ MB',
  'FileSize.GB': '%@ GB',
  'Message.ReplyActionButtonShowReceipt': '显示收据',
  'PeerInfo.Administrators': '管理员',
  'PeerInfo.Discussion': '讨论',
  'PeerInfo.Discussion.Add': '添加讨论群',
  'PeerInfo.Subscribers': '订阅者',
  'PeerInfo.SetAboutDescription': '你可以添加一段简介，让成员了解此聊天。',
  'Stickers.SuggestStickers': '通过 Emoji 推荐',
  'GroupPermission.Delete': '删除例外项',
  'Time.TomorrowAt': '明天 %@',
  'TwoStepAuth.SetPasswordHelp': '在新设备登录时，除了输入短信验证码外，还需输入此密码。',
  'TwoStepAuth.GenericHelp': '两步验证已开启\n在登录 Telegram 时，请输入之前所设的密码。',
  'TwoStepAuth.ChangePassword': '更改密码',
  'TwoStepAuth.RemovePassword': '关闭两步验证',
  'TwoStepAuth.SetupEmail': '设置恢复邮箱',
  'TwoStepAuth.ChangeEmail': '更改恢复邮箱',
  'TwoStepAuth.RecoveryTitle': '电子邮箱验证',
  'TwoStepAuth.RecoveryCode': '验证码',
  'TwoStepAuth.RecoveryCodeInvalid': '验证码无效，请重新输入。',
  'TwoStepAuth.RecoveryCodeExpired': '我们重新发送了六位验证码。',
  'TwoStepAuth.SetupHintTitle': '密码提示',
  'Undo': '撤销',
  'ChannelDirectMessages.Settings.Title': '私信',
  'ChannelDirectMessages.Settings.Off': '已关闭',
  'ChannelDirectMessages.Settings.Free': '免费',
  'ChannelDirectMessages.Settings.SwitchLabel': '允许私信',
  'PaymentTip': '小费',
  'PaymentTipOptional': '小费（可选）',
  'PaymentInvoiceLinkInvalid': '无效账单',
  'PaymentInfoHint': '您花费 **%1$s** 购买 **%2$s** 。',
  'SetAsEmojiStatus': '设为当前账号状态',
  'SetAsEmojiStatusInfo': '已设置表情状态。',
  'Quote': '引用',
  'NotificationsStoryMute2': '不接收动态通知',
  'NotificationsStoryUnmute2': '接收动态通知',
  'NotificationsStoryMutedHint': '已停用来自 **%s** 的动态通知。',
  'NotificationsStoryUnmutedHint': '**%s** 发布动态时您将收到一则通知提醒。',
  'DeleteChannelForAll': '为所有订阅者删除',
  'ChannelJoinRequest': '申请加入群组',
  'ActionGiftInbound': 'un1 已花费 **un2** 赠予您一份礼物',
  'ActionGiftOutbound': '您已花费 **un2** 赠予礼物',
  'ActionGiftPremiumView': '查看',
  'ChannelAntiSpam': '积极的反垃圾信息策略',
  'ChannelAntiSpamInfo': 'HSgram 会过滤更多的垃圾信息，但偶尔可能会影响普通消息。您可以在最近的操作中报告误报。',
  'ChannelHideMembers': '隐藏成员',
  'ChannelHideMembersInfo': '打开此选项可隐藏该群组的成员列表。管理员将仍然可见。',
  'ChannelSignMessagesWithProfile': '显示作者资料',
  'UserRestrictionsNoSendPhotos': '暂无照片',
  'UserRestrictionsNoSendVideos': '暂无视频',
  'UserRestrictionsNoSendMusic': '暂无音频',
  'UserRestrictionsNoSendDocs': '暂无文件',
  'UserRestrictionsNoSendVoice': '无权发送语音',
  'UserRestrictionsNoSendRound': '无权发送视频消息',
  'AddBot': '添加机器人',
  'EventLogRankSelfAdd': 'un1 已将自己的标签设置为 “%1$s”',
  'EventLogRankSelfEdit': 'un1 已将自己的标签从 “%1$s” 更改为 “%2$s”',
  'EventLogRankSelfRemove': 'un1 移除了自己的 “%1$s” 标签',
  'EventLogRankAdd': 'un1 已将 un2 的标签设置为 “%1$s”',
  'EventLogRankEdit': 'un1 已将 un2 的标签从 “%1$s” 更改为 “%2$s”',
  'EventLogRankRemove': 'un1 删除了 un2 的 “%1$s” 标签',
  'SponsoredMessage': '广告',
  'SponsoredMessageAd': '广告',
  'SponsoredMessageAdWhatIsThis': '这是什么？',
  'RevenueSharingAdsAlertSubtitle': 'HSgram 广告与其他平台上的广告大有不同。例如此广告：',
  'RevenueSharingAdsInfo1Title': '尊重您的隐私',
  'RevenueSharingAdsInfo1Subtitle': 'HSgram 上的广告不会使用您的个人信息，而是基于您所在的频道来展示的。',
  'RevenueSharingAdsInfo2Title': '帮助频道创造者',
  'RevenueSharingAdsInfo2Subtitle': 'HSgram 广告收入的 50% 将归广告频道的所有者所有。',
  'RevenueSharingAdsInfo3Title': '可以移除',
  'RevenueSharingAdsInfo3Subtitle': '您可以通过订阅 HSgram 高级版关闭广告，而等级为 %1$s 的频道可以为其订阅者移除这些广告。',
  'RevenueSharingAdsInfo4Title': '我可以投放广告吗？',
  'RevenueSharingAdsInfo4Subtitle2': '任何人都可以用极低的预算在这个频道投放广告。详情请查看 **HSgram 广告平台**。%1$s',
  'RevenueSharingAdsAlertButton': '了解',
  'TypeMessageIn': '%1$s 中的消息',
  'DeleteBan': '封禁 %1$s',
  'DeleteBanUsers': '封禁用户',
  'DeleteRestrict': '限制 %1$s',
  'DeleteRestrictUsers': '限制用户',
  'TranslateMessage': '翻译',
  'DeleteAllFromUsers': '删除该用户发送的所有消息',
  'DeleteAdditionalActions': '更多选项',
  'DeleteToggleBanUsers': '彻底封禁用户',
  'DeleteToggleBanUser': '彻底封禁此用户',
  'DeleteToggleRestrictUsers': '部分限制用户',
  'DeleteToggleRestrictUser': '部分限制此用户',
  'DeleteProceedBtn': '继续',
  'ReportInfo': '请输入与您的举报有关的任何其他细节。',
  'ReportHint': '更多细节……',
  'ReportSentInfo': 'HSgram 管理员将复核您的举报。感谢您的协助！',
  'SavedMessagesInfoQuote': '引用至此以收藏。',
  'CodeCopied': '代码已拷贝到剪贴板',
  'GlobalAttachPlainRestricted': '该群组不允许发送文本消息。',
  'GlobalAttachDocumentsRestricted': '这个群组不允许发送文档。',
  'GlobalAttachAudioRestricted': '此群组不允许发送音频。',
  'GlobalAttachPhotoRestricted': '此群组不允许发送图片。',
  'GlobalAttachVideoRestricted': '此群组不允许发送视频。',
  'GlobalAttachVoiceRestricted': '此群组不允许发送语音。',
  'GlobalAttachRoundRestricted': '这里不允许发送视频消息。',
  'GlobalAttachEmojiRestricted': '此群组不允许发送文本消息。',
  'FakeMessage': '假冒',
  'NoMessagesGreetingsDescription': '发送信息或点击下方的问候语。',
  'FwdMessageToSavedMessages': '消息已转发到 **我的收藏**。',
  'FwdMessagesToSavedMessages': '消息已转发到 **我的收藏**。',
  'LinkCopiedPrivateInfo': '此链接只对该聊天的成员有效。',
  'UsernameCopied': '用户名已复制到粘贴板',
  'BioCopied': '个人简介已复制至剪贴板。',
  'UsernameAlso': '同时 %1$s',
  'ClearRecentStickersAlertTitle': '清空最近使用的贴纸',
  'AddEmojiNotFound': '未找到此表情包。',
  'ChannelAutotranslation': '自动翻译消息',
  'TranslateMessages': '翻译消息',
  'ShowTranslateButton': '显示“翻译”按钮',
  'ShowTranslateChatButton': '翻译全部聊天记录',
  'DoNotTranslate': '无需翻译',
  'TelegramFeatures': 'HSgram功能',
  'TelegramFeaturesUrl': 'https://t.me/HSgramTips',
  'WebAppDisclaimerUrl': 'https://hsgram.org/tos/mini-apps',
  'Quality': '质量',
  'SearchAsList': '以列表显示',
  'SearchAsChat': '以聊天形式查看',
  'GifSavedHint': '已加入 GIF 动态图收藏。',
  'PrivacyMessagesContactsAndPremium': '我的联系人与高级版订阅用户',
  'PrivacyMessages': '消息',
  'PrivacyVoiceMessages': '语音消息',
  'PrivacyMessagesTitle': '谁可以给我发消息？',
  'PrivacyVoiceMessagesTitle': '谁可以给我发送语音或视频消息？',
  'PrivacyVoiceMessagesInfo': '您可以精确地控制谁可以向您发送语音或视频消息。',
  'PrivacyPaymentsPaymentInfoCleared': '支付信息已清除。',
  'PrivacyPaymentsShippingInfoCleared': '配送信息已清空。',
  'PrivacyPaymentsPaymentShippingCleared': '支付与配送信息已清空。',
  'BotWebViewOpenBot': '打开机器人',
  'BotWebViewReloadPage': '重新加载页面',
  'BotWebViewDeleteBot': '从菜单中移除',
  'BotWebViewChangesMayNotBeSaved': '所作的更改可能不会保存。',
  'BotWebViewCloseAnyway': '仍然关闭',
  'ActionTTLChanged': 'un1 已设置在 %1$s 之后自动删除消息',
  'ActionTTLYouChanged': '您已设置消息在 %1$s 后自动删除',
  'ActionTTLChannelChanged': '此频道中的消息将在 %1$s 后自动删除',
  'ActionTTLChannelDisabled': '此频道中的消息将不会被自动删除',
  'ActionTTLDisabled': 'un1 已停用自动删除计时器',
  'ActionTTLYouDisabled': '您关闭了自动删除定时器',
  'LimitReachedPinnedTopics': '抱歉，您最多只能置顶 %d 个话题。',
  'AreYouSureDeleteAndExitChannel': '您确定要删除并退出此频道吗？',
  'ViewsAndSharesChartTitle': '浏览和分享次数',
  'ReactionsByEmotionChartTitle': '表情回应',
  'StoryInteractionsChartTitle': '动态浏览和分享次数',
  'StoryReactionsByEmotionChartTitle': '动态回应',
  'ViewsPerStory': '每条动态的浏览量',
  'SharesPerStory': '每条动态的分享数',
  'ReactionsPerStory': '每条动态的表情回应',
  'ReactionsPerPost': '每个帖文的回应次数',
  'ViewStatistics': '查看统计数据',
  'VoipChannelJoinVoiceChatUrl': '加入直播',
  'LimitByPeriod': '时间限制',
  'LimitNumberOfUses': '按用户数量限制',
  'NewLink': '新链接',
  'TimeLimitHelp': '您可以设置该链接在一定时间后过期。',
  'UsesLimitHelp': '您可以设定链接在使用一定次数后自动失效。',
  'LinkCreatedeBy': '链接创建者',
  'RevokedLinks': '已撤销的链接',
  'DeleteLink': '删除链接',
  'LinkIsExpired': '此链接已过期。',
  'LinkIsExpiredLimitReached': '此链接已达到其使用上限。',
  'CreateNewLink': '新建链接',
  'DeleteAllRevokedLinks': '删除所有已废除的链接',
  'LinksCreatedByThisAdmin': '此管理员创建的邀请链接',
  'LinksCreatedByOtherAdmins': '由其他管理员创建的邀请链接',
  'InviteExpired': '邀请链接已失效。',
  'AccDescrTopic': '话题',
  'AccDescrQuizExplanation': '说明',
  'ChatThemeChangedYou': '您已将聊天主题更改为 %1$s',
  'ChatThemeChangedTo': '%1$s 将聊天主题设为 %2$s',
  'ChatThemeDisabled': '%1$s 已停用聊天主题',
  'ChatThemeDisabledYou': '您已停用聊天主题',
  'MediaZoomIn': '放大',
  'MediaZoomOut': '缩小',
  'ApproveNewMembers': '需要管理员批准',
  'ApproveNewMembersDescription': '启用此选项后，新用户加入前需得到管理员的批准。',
  'RequestToJoinGroupDescription': '加入该群需要获得管理员的批准。',
  'RequestToJoinChannelDescription': '此频道仅在管理员批准后才接受新订阅者。',
  'RequestToJoinSent': '加入请求已发送',
  'AddToGroup': '添加到群组',
  'AddToChannel': '添加至频道',
  'Dismiss': '拒绝',
  'RequestedToJoinAt': '在 %1$s 请求加入',
  'RequestToJoinGroupApproved': '您已获批加入群组',
  'RequestToJoinChannelApproved': '您已获批加入群组',
  'LinkNameHint': '链接名称（可选）',
  'LinkNameHelp': '仅管理员有权查看该名称',
  'MessageContainsEmojiPack': '此消息包含来自 %s 表情包的表情。',
  'MessageContainsReactionPack': '此表情回应是 %s 表情包中的一个表情。',
  'SendMessageAsTitle': '以哪个身份发送消息…',
  'OpenChannelPost': '查看帖子',
  'SavingContentTitle': '内容保护',
  'ChannelSettingsJoinTitle': '谁可以发送消息？',
  'ChannelSettingsJoinToSend': '仅成员',
  'ChannelSettingsJoinToSendInfo': '如果您希望用户在加入群组之后方可发送消息，请开启此功能。',
  'ChannelSettingsJoinRequest': '新成员审核',
  'ChannelSettingsJoinRequestInfo': '启用此选项后，新成员加入前需得到管理员的批准。',
  'Allow': '允许',
  'SessionsListInfo': 'HSgram 官方应用可用于 iPhone、iPad、Android、macOS、Windows 和 Linux。',
  'EnableReactions': '启用表情回应',
  'EnableReactionsChannelInfo': '允许订阅者对频道消息作出回应。',
  'EnableReactionsGroupInfo': '允许成员对群组消息作出表情回应。',
  'AvailableReactions': '可选择的回应',
  'DoubleTapSetting': '快速回应',
  'NobodyViewed': '无人已读',
  'ReadAllReactions': '将所有表情回应标记为已读',
  'ReadAllMentions': '全部提及已读',
  'Clear': '清空',
  'ReportChatIllegalDrugs': '违禁药品',
  'ReportChatPersonalDetails': '个人信息',
  'PrivacyPhoneInfo4': '此公开链接将打开与您的聊天',
  'ActionBotWebViewData': '来自 “%1$s” 按钮的数据已发送至机器人。',
  'BotRequestAttachPermission': '**%1$s** 请求作为选项添加到您的附件菜单，以便您可以从任何聊天中访问它。',
  'BotCantAddToAttachMenu': '无法将此机器人添加到附件菜单。',
  'BotAlreadyAddedToAttachMenu': '此机器人已经在您的附件菜单中。',
  'IncreaseLimit': '提升上限',
  'LimitReachedFolders': '您已达到 **%1$d** 个文件夹的限额。 您可以订阅 **HSgram 高级版**，将此上限翻倍至 **%2$d** 个文件夹。',
  'LimitReachedFoldersPremium': '您已经达到此帐号 **%1$d** 个文件夹的上限。',
  'LimitReachedFoldersLocked': '你已达到 %1$d 文件夹的上限。我们正在努力让你在未来提高此上限。',
  'LimitReachedChatInFolders': '抱歉，您无法在单个文件夹中添加超过 **%1$d** 个聊天。订阅 **HSgram 高级版** 后可将此上限提高至 **%2$d** 个聊天。',
  'LimitReachedChatInFoldersPremium': '抱歉，您无法在一个文件夹中添加超过 %1$d 个聊天，请创建新的文件夹。',
  'LimitReachedChatInFoldersLocked': '抱歉，您无法在此文件夹中添加超过 **%1$d** 个聊天。请再创建一个新的文件夹。我们在以后将尽力为您提高该限制。',
  'LimitReachedCommunities': '您已加入 **%1$d** 个群组或频道。请在加入新的之前先退出一些——或者订阅 **HSgram 高级版**，将此上限翻倍至 **%2$d** 个群组或频道。',
  'LimitReachedCommunitiesPremium': '您已经成为 %1$d 个群组和频道的成员了，请在加入新的之前退出一些群组或频道。',
  'LimitReachedCommunitiesLocked': '您已加入 **%1$d** 个群组或频道。请在加入新的之前先退出一些。我们正在努力能让你在未来提高此上限。',
  'LimitFree': '免费',
  'LimitPremium': '高级会员',
  'PremiumPreviewTags': '消息标签',
  'PremiumPreviewTagsDescription2': '使用标签整理收藏的消息，以便快速访问。',
  'GiftSubscriptionFor': '花费 %1$s 赠予订阅',
  'PricePerMonth': '%1$s / 月',
  'GiftPremium': '赠予高级版订阅',
  'GiftPremiumGifting': '赠送 Telegram 高级版',
  'GiftPremiumActivateForFree': '免费激活',
  'GiftPremiumActivateErrorTitle': '您已经拥有 HSgram 高级版',
  'GiftPremiumUseGiftBtn': '使用礼物',
  'GiftTelegramPremiumTitle': '赠予 HSgram 高级版',
  'GiftTelegramPremiumDescription': '将 **HSgram 高级版** 的专属功能赠予 **%1$s**。',
  'TelegramPremiumSubscribedTitle': '一切都已就绪！',
  'TelegramPremiumSubscribedSubtitle': '欢迎订阅 **HSgram 高级版**。您已成功解锁以下特权。',
  'PremiumTierAnnual': '按年',
  'PremiumTierSemiannual': '半年',
  'PremiumTierMonthly': '按月',
  'GroupsAndChannelsLimitTitle': '群组和频道',
  'GroupsAndChannelsLimitSubtitle': '加入多达 %d 个频道和大型群组',
  'PinChatsLimitTitle': '已置顶聊天',
  'PinChatsLimitSubtitle': '在主聊天列表中置顶高达 %d 个聊天',
  'PublicLinksLimitTitle': '公共链接',
  'PublicLinksLimitSubtitle': '保留高达 %d 个 t.me/username 链接',
  'SavedGifsLimitTitle': '保存 GIF 动态图',
  'SavedGifsLimitSubtitle': '在 GIF 动态图收藏中存储高达 %d 张 GIF 动态图',
  'FavoriteStickersLimitTitle': '贴纸收藏',
  'FavoriteStickersLimitSubtitle': '在贴纸收藏中存储高达 %d 张贴纸',
  'FoldersLimitTitle': '文件夹',
  'FoldersLimitSubtitle': '将您的聊天整理到 %d 个文件夹中',
  'ChatPerFolderLimitTitle': '每个文件夹内聊天数量',
  'ChatPerFolderLimitSubtitle': '在每个文件夹内添加高达 %d 个聊天',
  'ConnectedAccountsLimitTitle': '关联账户',
  'ConnectedAccountsLimitSubtitle': '使用不同的电话号码连接到 %d 个账号',
  'PremiumStickersShort': '高级版',
  'CaptionsLimitTitle': '说明文字',
  'CaptionsLimitSubtitle': '在图片和视频下使用更长的说明文字',
  'HideAd': '隐藏',
  'RemoveAds': '移除广告',
  'AboutRevenueSharingAds': '关于这些广告',
  'ReportAd': '举报广告',
  'ReportAdLearnMore': '了解更多有关我们的[广告政策和指南](https://ads.hsgram.org/guidelines)。',
  'AdHidden': '你将不再看到 HSgram 提供的广告。',
  'BioLimitTitle': '个人简介',
  'BioLimitSubtitle': '在个人介绍中添加更多文字，使用链接。',
  'ClearRecentStickersAlertMessage': '您确定要清空您所有最近使用的贴纸吗？',
  'LimitReachedPinDialogs': '您无法置顶超过 %1$d 个聊天。请取消一些置顶的聊天，或者订阅 **HSgram 高级版**，将此上限翻倍至 **%2$d** 个聊天。',
  'LimitReachedPinDialogsPremium': '抱歉，您最多只能置顶 %1$d 个聊天，请先取消置顶一些当前已置顶的聊天。',
  'LimitReachedPinDialogsLocked': '抱歉，您最多只能置顶 %1$d 个聊天，请先取消置顶一些当前已置顶的聊天。我们在以后将尽力为您提高该限制。',
  'TelegramPremiumUserGiftedPremiumDialogTitleWithPlural': '**%1$s** 已赠予您 %2$s 的HSgram 高级版订阅。',
  'TelegramPremiumUserGiftedPremiumDialogTitleWithPluralSomeone': '有人赠送了您一个 %1$s的 HSgram 高级版的订阅。',
  'TelegramPremiumUserGiftedPremiumDialogSubtitle': '您现在可以使用额外的功能了。',
  'TelegramPremiumUserGiftedPremiumOutboundDialogSubtitle': '**%1$s** 现在可以使用额外的功能了。',
  'Unlock': '解锁',
  'AllReactions': '所有表情回应',
  'SomeReactions': '部分表情回应',
  'NoReactions': '禁用表情回应',
  'OnlyAllowThisReactions': '仅允许这些表情回复',
  'EnableSomeReactionsInfo': '群组成员仅可使用已批准的表情回应消息。',
  'EnableAllReactionsInfo': '群组成员可以使用任何表情回应消息。',
  'DisableReactionsInfo': '群组成员无法对消息使用表情回应。',
  'SetEmojiStatusUntil1Hour': '设置为 1 小时',
  'SetEmojiStatusUntil2Hours': '设置为 2 小时',
  'SetEmojiStatusUntil8Hours': '设置为 8 小时',
  'SetEmojiStatusUntil2Days': '设置为 2 天',
  'UsernamesProfileHeader': '用户名顺序',
  'UsernameActivateLink': '激活链接',
  'UsernameDeactivateLink': '链接已失效',
  'UsernameLinkEditable': '点击以编辑',
  'UsernameLinkActive': '活跃',
  'UsernameLinkInactive': '不可用',
  'UsernameActivateLinkProfileMessage': '你想要将此链接显示在你的信息页面上吗？',
  'UsernameDeactivateLinkProfileMessage': '是否在您的信息页面上隐藏此链接？',
  'UsernameActivateLinkChannelMessage': '你想要将此链接显示在频道信息页面上吗？',
  'UsernameDeactivateLinkChannelMessage': '是否在频道信息页面上隐藏此链接？',
  'UsernameActivateErrorTitle': '活跃链接过多',
  'UsernameActivateErrorMessage': '抱歉，现有活跃公开链接过多，请先隐藏一个活跃公开链接。',
  'Hide': '隐藏',
  'Show': '显示',
  'UsernamesProfileHelp': '拖放链接以更改它们在您的信息页面上的显示顺序。',
  'UsernamesChannelHelp': '拖放链接以更改它们在频道信息页面上的显示顺序。',
  'NewTopic': '新的话题',
  'CreateTopicTitle': '请选择话题名称与图标',
  'CreateGeneralTopicTitle': '选择话题名称',
  'Discard': '放弃',
  'EditTopicHide': '在话题中显示',
  'EditTopicHideInfo': '如果“常规”主题处于隐藏状态，则群组成员可以在主题列表中下拉以查看该主题。',
  'NoTopics': '暂无主题',
  'CloseTopic': '锁定话题',
  'RestartTopic': '解锁话题',
  'SavedViewAsChats': '以聊天模式查看',
  'SavedViewAsMessages': '以消息模式查看',
  'TopicViewAsTopics': '以话题模式查看',
  'DeleteSelectedTopic': '您确定要删除 %s 吗?',
  'TopicProfileStatus': '在 %s',
  'ChannelTopicsDiscussionForbidden': '目前无法在频道的讨论群组中使用话题。',
  'ManageTopicsPermission': '管理话题',
  'CreateTopicsPermission': '创建话题',
  'TopicWasCreatedAction': '已创建 %s 话题',
  'AllChats': '所有聊天',
  'AnonymousNumber': '匿名号码',
  'AutoDeleteMessages': '自动删除消息',
  'ActionAttachMenuBotAllowed': '当您将此机器人添加到附件菜单中时，您已允许此机器人向您发送消息',
  'EnablePhotoSpoiler': '罩住图片',
  'DisablePhotoSpoiler': '取消遮罩',
  'Remove': '移除',
  'Chats': '%1$d 个聊天',
  'Files': '%1$d 个文件',
  'Voice': '%1$d 条语音消息',
  'DoNotTranslateLanguage': '不用翻译 %s',
  'TranslateToButton': '翻译为%s',
  'ShowOriginalButton': '显示原文',
  'DynamicPackOrder': '贴纸包动态顺序',
  'DynamicPackOrderInfo': '将最近使用的贴纸包自动置于前列。',
  'InviteLinkSentSingle': '已将邀请链接发送给 **%s**。',
  'UnsavedChanges': '未保存的更改',
  'ActionSetWallpaperForThisChatSelf': '您已为此聊天设置新壁纸',
  'ActionSetWallpaperForThisChannel': '频道已设立新壁纸',
  'ActionSetWallpaperForThisGroup': '群组已设置新壁纸',
  'ActionSetWallpaperForThisGroupByUser': '%s 已设置新壁纸',
  'ActionSetSameWallpaperForThisChatSelf': '您已设置与对方相同的壁纸',
  'ActionSetWallpaperForThisChat': '%s 为此聊天设置了新壁纸',
  'ActionSetWallpaperForThisChatBoth': '%s 已为此聊天设置新壁纸',
  'ActionSetSameWallpaperForThisChat': '%s 在此聊天中已为您设置与其相同的壁纸',
  'ActionSetWallpaperForThisChatSelfBoth': '您已为自己和 %s 设置新壁纸',
  'SelectAll': '全选',
  'DeselectAll': '取消全选',
  'BotWebAppInstantViewOpen': '打开应用',
  'DeleteStoryTitle': '删除动态',
  'DeleteStorySubtitle': '您确定想要删除此动态吗？',
  'DeleteStoriesTitle': '删除动态',
  'NobodyViews': '还没有人看过',
  'NobodyViewsArchived': '没有可用的查看记录',
  'MyStory': '我的动态',
  'Story': '动态',
  'StoryStatistics': '动态统计数据',
  'PostStatistics': '贴文统计数据',
  'ExpiredStory': '过期的动态',
  'ProfileStories': '动态',
  'ProfileStoriesArchiveHint': '除非将其发布至个人资料页，否则只有您能查看已归档的动态。',
  'ProfileStoriesArchiveChannelHint': '仅频道管理员可以查看已归档动态，除非动态已保存在频道资料页。',
  'ProfileStoriesArchiveGroupHint': '只有群组管理员才能查看已归档的动态，除非这些动态已发布到群组页面上。',
  'StoryPinnedToProfile': '动态已发布至您的个人资料页。',
  'StoryPinnedToPosts': '动态已保存至频道资料页',
  'StoryArchivedFromProfile': '此动态已从您的个人资料页隐藏。',
  'StoryUnpinnedFromPosts': '已从频道资料页移除动态',
  'StoriesMovedToContacts': '**%s** 的动态已移至 **归档**.',
  'StoriesMovedToDialogs': '**%s** 的动态已移至 **聊天**.',
  'ViewStory': '查看动态',
  'StorySharedTo': '动态已转发至 **%s**。',
  'StorySharedToSavedMessages': '已将动态转发到**我的收藏**',
  'StoryCloseFriendsHint': '您能看到这条动态是因为 **%s** 将您添加到了密友列表中。',
  'StorySelectedContactsHint': '只有 **%s** 选择的部分用户可以查看该动态。',
  'StoryContactsHint': '只有 **%s** 的联系人可以查看此动态。',
  'ArchivedStories': '已归档的动态',
  'SavedStories': '已发布的动态',
  'ExpiredStoryMention': '提到您的动态已无法访问',
  'ArchiveSettings': '归档设置',
  'ArchivePeerStories': '隐藏动态',
  'UnarchiveStories': '取消隐藏动态',
  'PremiumStoriesPriority': '优先显示',
  'PremiumStoriesPriorityDescription': '您的动态将始终优先展示，因此可以获得更多浏览量。',
  'PremiumStoriesStealth': '隐身模式',
  'PremiumStoriesStealthDescription': '隐藏您曾浏览其他用户动态的痕迹。',
  'PremiumStoriesViews': '永久访客历史',
  'PremiumStoriesViewsDescription': '查看谁打开过您的动态——即使在动态过期后仍能查看。',
  'PremiumStoriesExpiration': '过期选项',
  'PremiumStoriesExpirationDescription': '为您的动态设置自定义过期时间，比如 6 小时或 48 小时。',
  'PremiumStoriesSaveToGallery': '将动态保存到相册',
  'PremiumStoriesSaveToGalleryDescription': '保存其他用户未开启保护的动态。',
  'PremiumStoriesCaption': '更长的说明文字',
  'PremiumStoriesCaptionDescription': '为您的动态添加 10 倍长的说明文字——最多 2048 个字符。',
  'PremiumStoriesFormatting': '链接和格式',
  'PremiumStoriesFormattingDescription': '在动态说明文字中添加链接和格式。',
  'StoryViewLocation': '查看位置 >',
  'SaveToPosts': '发布至个人资料页',
  'RemoveFromPosts': '从动态中删除',
  'LinkForBoosting': '助推链接',
  'Boosts': '助推',
  'BoostsLevel': '等级 %d',
  'BoostsLevel2': '等级',
  'BoostingCongratulations': '恭喜!',
  'BoostingReceivedGiftFrom': '您已收到来自 %s 的礼物。',
  'BoostingReceivedGiftNoName': '您已收到礼物。',
  'BoostingReceivedGiftDuration': '您的奖品是 %s 的 **HSgram 高级版**订阅。',
  'BoostingUnclaimedPrize': '尚未领取的奖品',
  'BoostingYouHaveUnclaimedPrize': '您从 **%s** 已获得一份尚未领取的奖品',
  'BoostingUnclaimedPrizeDuration': '此奖品是 %s 的 **HSgram 高级版** 订阅。',
  'BoostingReceivedPrizeFrom': '您在 **%s** 发起的赠品活动中赢得了奖品。',
  'BoostingReceivedPrizeDuration': '你的奖品是 %s 的 **HSgram 高级版** 订阅。',
  'BoostingReceivedGiftOpenBtn': '公开礼物链接',
  'BoostingGiveawayJustStarted': '%s 刚刚发起一场抽奖活动，向其订阅者赠送 HSgram 高级版订阅。',
  'BoostingGiveawayDeleteMsgTitle': '删除公告',
  'BoostingGiveawayDeleteMsgText': '删除此消息不会取消抽奖活动——仍旧将在 **%s** 选出获奖者。一旦消息被删除，将无法恢复抽奖活动公告。',
  'BoostingGetBoostsViaGifts': '通过赠品助推',
  'BoostingUseLink': '使用链接',
  'BoostingShareThisLink': '将此链接分享给您的订阅者，以得到更多助推。',
  'BoostingSelectPaidGiveaway': '请选择您已支付的赠品活动以进行设定。',
  'BoostingPremium': 'HSgram 高级版',
  'BoostingStars': 'HSgram 星星',
  'BoostingUnclaimed': '尚未领取',
  'BoostingToBeDistributed': '待分发',
  'BoostingShortMonths': '%1$d 个月',
  'BoostingGiveaway': '抽奖活动',
  'BoostingRecipientWillBeSelected': '抽奖活动结束后将选择接收者。',
  'BoostingIncompleteGiveaway': '未完成的抽奖活动',
  'BoostingNoRecipient': '无接收者',
  'BoostingSelectCountry': '选择国家',
  'BoostingTelegramPremiumFor': '%s 个月的 HSgram 高级版订阅',
  'BoostingUsedGiftLink': '使用过的礼品链接',
  'BoostingGiftLink': '礼品链接',
  'BoostingGetMoreBoosts': '通过向您的订阅者赠予 Telegram 高级版来为您的频道获取更多助推。',
  'BoostingGetMoreBoosts2': '通过赠送奖品来为您的频道获得更多的助推和订阅者。',
  'BoostingLinkUsed': '此链接用于启用 **HSgram 高级版** 订阅。',
  'BoostingLinkAllows': '此链接允许您启用 **HSgram 高级版** 订阅。',
  'BoostingLinkAllowsToUser': '此链接允许 **%1$s** 启用 **HSgram 高级版** 订阅。',
  'BoostingLinkAllowsAnyone': '此链接允许任何人启用 **HSgram 高级版** 订阅。',
  'BoostingLinkNotActivated': '此链接尚未启用。',
  'BoostingFrom': '来自',
  'BoostingTo': '到',
  'BoostingGift': '赠礼',
  'BoostingYouWereSelected': '你已被频道选中',
  'BoostingReason': '事由',
  'BoostingDate': '日期',
  'BoostingFromAllCountries': '来自所有国家',
  'BoostingUsedLinkDate': '此链接已于 %s 使用。',
  'BoostingStarsQuantityPrizes': '获奖者数量',
  'BoostingStarsQuantityPrizesInfo': '选择您要为多少获奖者发放星星。',
  'BoostingStarsOptions': '可分发的星星',
  'BoostingStarsOptionsInfo': '选择赠送多少颗星星以及每年获得多少次助推。',
  'BoostingGiftLinkForwardedTo': '礼物链接已转发到 **%1$s**。',
  'BoostingGiftLinkForwardedToSavedMsg': '礼物链接已转发到 **我的收藏**。',
  'BoostingStarsGiveawayAdditionPrizeHint': '如果您想在赠送星星的同时，额外为获奖者提供您自己的奖品，请开启此选项。',
  'BoostingGiveawayEnd': '抽奖活动已结束',
  'BoostingGiveawayPrivateChannel': '这是私人频道',
  'BoostingGiveawayPrivateChannelWarning': '您确定要新增私人频道吗？如果没有邀请链接，用户将无法加入。',
  'BoostingGiveawayYouNotWon': '您在此次抽奖活动中没有获奖。',
  'BoostingGiveawayViewPrize': '查看我的奖品',
  'BoostingGiveawayCanceledByPayment': '该频道通过撤销付款的方式取消了奖品。',
  'BoostingGiveawayNotEligible': '您没有资格参加此赠品活动，因为您是在 **%1$s** 即活动开始之前加入此频道的。',
  'BoostingGiveawayNotEligibleAdmin': '您没有资格参与此赠品活动，因为您是参与频道的管理员 (**%1$s**)。',
  'BoostingGiveawayNotEligibleCountry': '您没有资格参加此赠品活动，因为您所在的国家未包含在赠品活动条款中。',
  'BoostingOnlyRecipientCode': '只有接收者可以看到链接。',
  'BoostingStartGiveawayConfirmTitle': '开始抽奖活动',
  'BoostingStartGiveawayConfirmText': '您确定要现在开始抽奖活动吗？',
  'BoostingMoreBoostsNeeded': '需要更多助推',
  'BoostingRemoveBoostFrom': '移除您的助推',
  'BoostingAvailableIn': '将于 %1$s 可用',
  'BoostingHowItWork': '了解更多',
  'BoostingGiveAwayAbout': '关于此抽奖活动',
  'BoostingGiveAwayFromCountries': '来自 %1$s',
  'BoostingWinnersDate': '**选定获奖者的日期**',
  'BoostingGiveawayPrizes': '**抽奖奖品**',
  'BoostingGiveawayResultsMsgAllWinnersReceivedLinks': '所有获奖者都已在私密消息中收到礼物链接。',
  'BoostingGiveawayMsgParticipants': '**参与者**',
  'PremiumSubscribers': 'Telegram 高级版订阅者',
  'BoostsExisting': '活跃助推',
  'BoostsToLevel': '助推以提升等级',
  'BoostChannel': '助推频道',
  'BoostGroup': '助推群组',
  'BoostLinkButton': '助推',
  'BotWebAppDisclaimerSubtitle': '您即将使用一个 **不属于 HSgram** 的独立第三方小程序。您必须同意小程序使用条款后才能继续。',
  'YouBoostedChannel': '您助推了频道！',
  'YouBoostedGroup': '您已助推群组',
  'PremiumNeeded': '需要订阅 Telegram 高级版',
  'PremiumNeededForBoosting': '只有 **HSgram 高级版** 订阅者可以助推频道。您是否要订阅 **HSgram 高级版**？',
  'CantBoostTooOften': '不能频繁助推！',
  'CantBoostTooOftenDescription': '您每天只能更改一次助推的频道。 您可以在 **%s** 后再次助推。',
  'BotAttachMenuShortcatAddedAttachAndSide': '**%s** 快捷方式已添加至附件菜单和侧边栏。',
  'BotAttachMenuShortcatAddedSide': '**%s** 快捷方式已添加到侧边栏中。',
  'BotAttachMenuShortcatAddedAttach': '**%s** 快捷方式已添加到附件菜单中。',
  'TermsOfUse': '使用条款',
  'ChannelNeedBoostsDescriptionForNewFeatures': '**%1$s** 需要 %2$s 来解锁新功能。',
  'NoBoostersHint': '目前没有用户助推您的频道',
  'BoostsMaxLevelReached': '已达到最高等级',
  'ReplyToDialog': '回复...',
  'ReplyTo': '回复 %s',
  'ReplyToQuote': '回复来自 %s 的引文',
  'ReplyToAnotherChat': '在另一个聊天中回复',
  'ReplyPrivate': '该回复来自私聊。',
  'QuotePrivate': '该引文来自私聊',
  'DoNotForward': '取消转发',
  'DoNotReply': '取消回复',
  'DoNotQuote': '取消引用',
  'CopyCode': '复制代码',
  'SimilarChannels': '相似频道',
  'MoreSimilar': '更多频道',
  'UnlockSimilar': '解锁更多频道',
  'MyNotes': '我的笔记',
  'HideReadTime': '隐藏已读时间',
  'HideReadTimeInfo': '对无法看到您最后上线时间的用户隐藏您的已读时间。如果您开启此功能，对方的已读时间也会对您隐藏（除非您是高级版订阅用户）。 此设定不影响群聊。',
  'PmReadShowWhen': '显示时间',
  'PrivacyLastSeenPremium': '订阅 HSgram 高级版',
  'PrivacyLastSeenPremiumInfo': '如果您订阅了 Telegram 高级版，您可以看到其他用户的最后上线时间及已读时间，即使您对其隐藏了自己的最后上线时间及已读时间（除非对方明确限制）。',
  'PrivacyLastSeenPremiumForPremium': '订阅 HSgram 高级版',
  'PrivacyLastSeenPremiumInfoForPremium': '因为您是 HSgram 高级版订阅者，所以您将看到启用分享的所有用户的最后上线和已读时间 - 即使您已隐藏自己的。',
  'PremiumReadHeader1': '显示您的已读时间',
  'PremiumReadText1': '若要查看 **%s** 的已读时间，您需显示您自己的已读时间...',
  'PremiumReadText1Locked': '为查看 **%s** 何时已读消息，请先开始显示您自己的已读时间。',
  'PremiumReadButton1': '显示我的已读时间',
  'PremiumReadHeader2': '升级为高级版',
  'PremiumReadText2': '订阅后您将可以看到 **%s** 的已读时间，而无需显示您的已读时间。',
  'PremiumReadButton2': '订阅 HSgram 高级版',
  'PremiumLastSeenHeader1': '显示您的最后上线时间',
  'PremiumLastSeenText1': '若要查看 **%s** 的最后上线时间，您需显示您自己的最后上线时间...',
  'PremiumLastSeenText1Locked': '为查看 **%s** 最后在线时间，请先开始显示您自己的最后在线时间。',
  'PremiumLastSeenButton1': '显示我的最近上线的时间',
  'PremiumOr': '或',
  'PremiumLastSeenHeader2': '升级为高级版',
  'PremiumLastSeenText2': '订阅后您将可以看到 **%s** 的最后上线时间，而无需显示您的最后上线时间。',
  'PremiumLastSeenButton2': '订阅 HSgram 高级版',
  'StatusHiddenShow': '何时？',
  'PremiumLastSeenSet': '您最后上线的时间已设为可见。',
  'PremiumReadSet': '您的已读时间已设为可见。',
  'OnlyPremiumCanMessage': '%s 只接受来自高级版订阅用户的消息。**了解更多...**',
  'SavedTagRemoveTag': '移除标签',
  'SavedTagLabelTag': '添加名称',
  'SavedTagRenameTag': '编辑名称',
  'SavedTagLabelPlaceholder': '名称',
  'SavedTagLabelTagText': '您可以使用文本给表情标签起一个名字。',
  'SavedTagFilterByTag': '依据标签进行筛选',
  'PremiumPreviewLastSeen': '最后上线时间',
  'PremiumPreviewLastSeenDescription': '即使您已将其隐藏，也可查看其它用户的最后上线及已读时间。',
  'PremiumPreviewMessagePrivacy': '消息隐私',
  'PremiumPreviewMessagePrivacyDescription': '限制来自陌生人的消息或对收到的消息收费。',
  'BusinessHoursNextDay': '%s (明天)',
  'BusinessHoursProfile': '营业时间',
  'BusinessHoursProfileOpen': '24 小时营业',
  'BusinessHoursProfileFullOpen': '7 × 24 小时营业',
  'BusinessHoursProfileClose': '休息',
  'BusinessHoursProfileNowOpen': '营业中',
  'BusinessHoursProfileNowClosed': '已关闭',
  'BusinessHoursProfileSwitchLocal': '当地时间',
  'BusinessHoursProfileSwitchMy': '你本地的时间',
  'BusinessProfileLocation': '位置',
  'BusinessHoursCopied': '已复制营业时间',
  'BusinessLocationCopied': '已复制企业地址',
  'DownloadSpeedLimited': '下载速度受限',
  'UploadSpeedLimited': '上载速度受限',
  'ChannelsTab': '频道',
  'ForwardedFrom': '转发自',
  'AddEffectMessageHint': '添加动画特效',
  'AnimatedEffectPremium': '订阅 **HSgram 高级版** 添加此动画特效。',
  'StickerEffects': '贴纸特效',
  'Confirm': '确认',
  'MenuTelegramStars': '我的星星',
  'TelegramStars': 'HSgram 星星',
  'TelegramStarsGift': '赠送星星给朋友',
  'StarsBalance': '余额',
  'StarsTransactionsAll': '所有交易',
  'StarsTransactionsIncoming': '进账',
  'StarsTransactionsOutgoing': '出账',
  'StarsMediaPurchaseCompleted': '媒体已解锁',
  'StarsConfirmPurchaseTitle': '确认购买',
  'TonNeededTitle': '需要 %s TON',
  'StarsNeededText': '购买 **星星** 并在 **%s** 和其他小程序中使用。',
  'CaptionAbove': '将说明文字上移',
  'CaptionBelow': '将说明文字下移',
  'AddFactCheck': '添加事实查核',
  'EditFactCheck': '编辑事实查核',
  'FactCheck': '事实核查',
  'FactCheckWhat': '这是什么？',
  'FactCheckDialog': '事实核查',
  'FactCheckPlaceholder': '添加事实或背景',
  'FactCheckToast': '此澄清是由 Telegram 提供的。',
  'FactCheckFooter': '此澄清是由 Telegram 提供的。',
  'FactCheckEdited': '已更新事实核查。',
  'FactCheckDeleted': '已移除事实核查。',
  'StarsTransactionID': '交易号',
  'StarsTransactionIDCopied': '已将交易号复制到剪贴板',
  'StarsTransactionDate': '日期',
  'StarsRefunded': '退款',
  'StarsFailed': '失败',
  'StarsPending': '处理中',
  'StarsTransactionMedia': '媒体',
  'StarMediaPurchase': '媒体购买',
  'GiftStarsTitle': '赠送星星',
  'GiftStarsSubtitle': '有了星星，**%s** 将可以解锁 HSgram 上的内容和服务。',
  'GiftStarsSubtitleLinkName': '**请查看示例 >**',
  'ActionGiftStarsSubtitle': '有了星星，**%s** 就可以解锁 HSgram 上的内容和服务。',
  'ActionGiftStarsSubtitleYou': '使用星星解锁 HSgram 上的內容和服务。',
  'StarsGiftReceived': '收到礼物',
  'StarsGiveawayPrizeReceived': '收到礼物',
  'StarsGiftSent': '送出的礼物',
  'SearchAppsExamples': '例子',
  'StarsReactionTitle': '以星星做出回应',
  'StarsReactionText': '选择您想要送出多少颗星星给 **%s** 以支持此贴文。',
  'StarsReactionTopSenders': '星星打赏榜',
  'StarsReactionShowMeInTopSenders': '在星星打赏榜上显示我',
  'StarsReactionAnonymous': '匿名',
  'ChannelSignProfilesInfo': '允许管理员以他们的频道或个人账号身分发布內容，并链接到他们的个人资料。',
  'Report2Comment': '添加评论',
  'Report2CommentOptional': '添加评论 (可选)',
  'Report2Send': '发送举报',
  'Reported2': 'HSgram 管理员将会检视您的举报。感谢您！',
  'DisableSharing': '禁用分享',
  'EnableSharing': '启用分享',
  'AccountSettings.Notifications': '通知和声音',
  'AccountSettings.PrivacyAndSecurity': '隐私和安全',
  'AccountSettings.Filters': '聊天文件夹',
  'AccountSettings.Language': '语言',
  'ChatList.Filter.List.Title': '聊天文件夹',
  'Telegram.GeneralSettingsViewController': '通用设置',
  'Telegram.NotificationSettingsViewController': '通知',
  'Telegram.LanguageViewController': '语言',
  'Premium.Boarding.Title': 'HSgram 高级版',
  'Chat.Menu.SendGift': '赠送礼物',
  'StarGiftSendGift': '赠送礼物',
  'Peer.Status.justNow': '刚刚上线',
  'Peer.Status.Today': '今天',
  'Peer.Status.Yesterday': '昨天',
  'Peer.Status.LastSeenAt': '%@ %@ 最后上线',
  'Peer.Status.minAgo': {
    'one_value': '%d 分钟前上线',
    'other_value': '%d 分钟前上线'
  },
  'LastSeen.HoursAgo': {
    'one_value': '%d 小时前上线',
    'other_value': '%d 小时前上线'
  },
  'Peer.Status.Member': {
    'one_value': '%d 位成员',
    'other_value': '%d 位成员'
  },
  'Peer.Status.Subscribers': {
    'one_value': '%d 位订阅者',
    'other_value': '%d 位订阅者'
  },
  'VoiceChat.Status.Members': {
    'one_value': '%d 位参与者',
    'other_value': '%d 位参与者'
  },
  'RecentActions': '近期操作',
  'HSgram.DisableSocialActions.Section': '成员互动',
  'HSgram.DisableSocialActions.Title': '禁止私聊',
  'HSgram.DisableSocialActions.Caption': '开启后，普通成员不能在群内打开成员资料发起私聊，@成员也会限制为管理员。',
  'HSgram.DisableSocialActions.Blocked': '本群禁止私聊',
  'Back': '返回',
  'Next': '下一步',
  'Error.SomethingWentWrong': '出错了，请稍后重试'
};

export default zhCN;
